name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
  ANOTHER_INPUT:
    description: "Just another input"
    required: true
    default: "$(date +%F)"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "film"
  color: "orange"
